# Generated by Django 5.2.8 on 2025-11-29 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, unique=True, verbose_name='Type')),
                ('title_template', models.CharField(max_length=255, verbose_name='Template titre')),
                ('message_template', models.TextField(verbose_name='Template message')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template de notification',
                'verbose_name_plural': 'Templates de notification',
                'db_table': 'notification_templates',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('account_created', 'Compte créé'), ('order_created', 'Commande créée'), ('order_accepted', 'Commande acceptée'), ('order_refused', 'Commande refusée'), ('order_preparing', 'Commande en préparation'), ('order_ready', 'Commande prête'), ('order_assigned', 'Commande assignée au livreur'), ('order_picked_up', 'Commande récupérée'), ('order_in_delivery', 'Commande en livraison'), ('order_delivered', 'Commande livrée'), ('order_cancelled', 'Commande annulée'), ('delivery_assigned', 'Livraison assignée'), ('delivery_accepted', 'Livraison acceptée'), ('delivery_refused', 'Livraison refusée'), ('delivery_pickup', 'Récupération effectuée'), ('delivery_in_progress', 'Livraison en cours'), ('delivery_completed', 'Livraison complétée'), ('payment_received', 'Paiement reçu'), ('payment_failed', 'Paiement échoué'), ('rating_received', 'Note reçue')], max_length=50, verbose_name='Type')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Données additionnelles')),
                ('order_id', models.IntegerField(blank=True, null=True, verbose_name='ID Commande')),
                ('delivery_id', models.IntegerField(blank=True, null=True, verbose_name='ID Livraison')),
                ('related_user_id', models.IntegerField(blank=True, null=True, verbose_name='ID Utilisateur lié')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lue')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mise à jour')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.clientdevice', verbose_name='Appareil')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device', '-created_at'], name='notificatio_device__0fb3e7_idx'), models.Index(fields=['user', '-created_at'], name='notificatio_user_id_611c58_idx'), models.Index(fields=['is_read'], name='notificatio_is_read_3f8c44_idx')],
            },
        ),
    ]
